name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Adjust if you want it to run on other branches

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t 420696663/lerngalerie:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker Image
      run: docker push 420696663/lerngalerie:latest
